# Generated by Django 5.0.4 on 2024-04-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='path',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
